name: CI

on:
  push:
    branches:
    - main
    tags:
    - v[0-9]+.[0-9]+.[0-9]+**
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Start Blaze FHIR Server
      run: docker-compose up -d

    - name: Wait for Blaze FHIR Server Running
      uses: ifaxity/wait-on-action@v1
      with:
        resource: http://localhost:8080/health
        timeout: 60000

    - name: Initialize Test Data
      run: bash init-testdata.sh

    - name: Run Test Queries
      env:
        SUCCESS_URI: "http://localhost:8080/fhir/Consent?mii-provision-provision-code-type=2.16.840.1.113883.3.1937.777.24.5.1.1$permit"
        FAILURE_URI: "http://localhost:8080/fhir/Consent?mii-provision-provision-code-type=2.16.840.1.113883.3.1937.777.24.5.1.1$deny"
      run: |
        curl -s --fail "$SUCCESS_URI" | jq -e '.total == 1'
        curl -s --fail "$FAILURE_URI" | jq -e '.total == 0'

  build:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker meta
      id: docker-meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/num-codex/blaze
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.docker-meta.outputs.tags }}
        labels: ${{ steps.docker-meta.outputs.labels }}
